### ISSUE TITLE
API Structure

### ISSUE THREAD

**Issue by BruceCodesGithub** [Mr-Conos/Rock-API#1]
# Resource
Why not use FastAPI to create the API? FastAPI offers more resources.

# Build
Moreover, the architecture of this project can be better

```
Rock-API
│   README.md 
│
└───api
│   │   main.py   
└───tests
    │   test1.py
    │   test2.py
```

And the architecture of the API itself can be improved too

mrconos.pythonanywhere.com/rock
  - `/post` - upload a new rock
  - `/random` - get a random rock from the API
  - `/get` - get a specific rock by name/ID

# Other features that can be added
- An unique ID for every rock
- Search for rocks
- Rocks upload and receive by `base64`

**Comment by BruceCodesGithub** [comment]
How serious are you about this API?

**Comment by Mr-Conos** [comment]
Most of this has been implemented for official release.
